#!/bin/zsh

session="|Desk"

if tmux has-session -t $session 2>/dev/null; then
    echo "Session '$session' exists，do you want to?\n[a(ttach)/n(ew)/c(ancel)]..."
    read choice
    if [ "$choice" = "a" ]; then
        tmux attach-session -t $session
    elif [ "$choice" = "n" ]; then
        tmux new-session -s "|Desk_new" -n "|Home" "neofetch;sleep 2;$HOME/uTUI/desktop.sh"\; set-option prefix C-a \; bind-key C-a send-pre

    else
        exit 0;
    fi 
else
  echo "Session '$session' doesn't exist，setting..."
  tmux new-session -s "$session" -n "|Home" "neofetch;sleep 2;$HOME/uTUI/desktop.sh"\; set-option prefix C-a \; bind-key C-a send-pre
fi
